use_frameworks!

platform :ios, '9.0'

target 'SSQBaseComponents_Example' do
  pod 'SSQBaseComponents', :path => '../'

  target 'SSQBaseComponents_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
